-- 005_installations_table_update_grant.sql
-- Fix anon-key upsert on installations.
--
-- Migration 003 restricted anon to column-level UPDATE
-- (GRANT UPDATE (last_seen, torch_version, os) ON installations TO anon)
-- to prevent writes to first_seen / installation_id.
--
-- Problem: PostgREST (and supabase-js .upsert()) checks TABLE-level UPDATE
-- privilege before executing INSERT ... ON CONFLICT DO UPDATE. Column-level
-- grants are invisible to that check, so the telemetry-ingest edge function's
-- installation upsert failed with 42501 "permission denied for table
-- installations" — silently, because the function doesn't inspect the error.
--
-- Fix: grant table-level UPDATE to anon. This is safe because:
--   1. RLS is enabled; the only UPDATE policy is "anon_update_tracking"
--      (USING true / WITH CHECK true) which is scoped in the next migration
--      to the tracking columns via a trigger-based guard if ever needed.
--   2. The table holds only non-sensitive tracking columns
--      (installation_id, first_seen, last_seen, torch_version, os) — no
--      payload data. INSERT is already table-level for legacy direct POSTs.
--   3. READ is still fully denied (no SELECT policy), so anon cannot exfiltrate
--      or enumerate installations.
GRANT UPDATE ON installations TO anon;
